### ISSUE TITLE
cannot add new categories and tags

### ISSUE THREAD

**Issue by ghost** [nihgwu/hexo-hey#17] opened 2016-01-05 18:30 UTC
https://github.com/nihgwu/hexo-hey/issues/13#issuecomment-160511625
跟他的情况一样，如果选择已有的分类或标签是可以的，但是新添加分类或标签就不行
无论是中、英文标签都不行。

环境：win7, firefox38, hexo-hey 0.4.0

另外有个小问题，编辑a文章后会隐藏了，找不到，只要新建另个一个文章b，文章a又出现了。

以上情况在你的demo里测试都能重现

**Comment by nihgwu** [comment] 2016-01-06 16:15
the first one should be a platform related issue and i can't reproduce it, i will check it when asap
the later one i have noticed it and i have created a #8 to solve it, but i can't reproduce it on my mac either, while the demo host on linux server does but hard to debug
thanks and i'm trying to close this issue

**Comment by nihgwu** [comment] 2016-01-07 07:46
I've test it on win10+firefox42+hexo-heyv0.4.1 and still can't reproduce it, do you click `Enter` after edit the cats and tags to create chips?

**Comment by ghost** [comment] 2016-01-08 07:15
i just add categories and tags , click publish, not working.

i add categories click Enter and publish, it works

(最好能添加说明要按回车键)

**Closed as completed** 2016-01-08 07:15 UTC
